// Code generated by go-gen-json. DO NOT EDIT.
package examples

import (
	"bytes"
	"encoding/json/jsontext"
	"errors"
)

func (p *BasicStruct) UnmarshalJSON(b []byte) error {
	d := jsontext.NewDecoder(bytes.NewReader(b))
	return p.UnmarshalJSONFrom(d)
}

func (p *BasicStruct) UnmarshalJSONFrom(d *jsontext.Decoder) error {
	var (
		t   jsontext.Token
		err error
	)
	t, err = d.ReadToken()
	if err != nil {
		return err
	}
	if t.Kind() != '{' {
		return errors.New("expected object start, got " + string(t.Kind()))
	}
	for d.PeekKind() != '}' {
		t, err = d.ReadToken()
		if err != nil {
			return err
		}
		if t.Kind() != '"' {
			return errors.New("expected string, got " + string(t.Kind()))
		}
		switch t.String() {
		case "name":
			t, err = d.ReadToken()
			if err != nil {
				return err
			} 
			if t.Kind() != '"' {
				return errors.New("expected string, got " + string(t.Kind()))
			}
			(*p).Name = string(t.String())
		case "age":
			t, err = d.ReadToken()
			if err != nil {
				return err
			}
			if t.Kind() != '0' {
				return errors.New("expected number, got " + string(t.Kind()))
			}
			(*p).Age = int(t.Int())
		case "email":
			t, err = d.ReadToken()
			if err != nil {
				return err
			} 
			if t.Kind() != '"' {
				return errors.New("expected string, got " + string(t.Kind()))
			}
			(*p).Email = string(t.String())
		case "active":
			t, err = d.ReadToken()
			if err != nil {
				return err
			}
			if t.Kind() != 't' && t.Kind() != 'f' {
				return errors.New("expected bool, got " + string(t.Kind()))
			}
			(*p).Active = t.Kind() == 't'
		}
	}
	_, _ = d.ReadToken()
	return nil
}
