// Code generated by go-gen-json. DO NOT EDIT.
package examples

import (
	"bytes"
	"encoding/json/jsontext"
	"errors"
)

func (p *EmptyStruct) UnmarshalJSON(b []byte) error {
	d := jsontext.NewDecoder(bytes.NewReader(b))
	return p.UnmarshalJSONFrom(d)
}

func (p *EmptyStruct) UnmarshalJSONFrom(d *jsontext.Decoder) error {
	var (
		t   jsontext.Token
		err error
	)
	t, err = d.ReadToken()
	if err != nil {
		return err
	}
	if t.Kind() != '{' {
		return errors.New("expected object start, got " + string(t.Kind()))
	}
	for d.PeekKind() != '}' {
		t, err = d.ReadToken()
		if err != nil {
			return err
		}
		if t.Kind() != '"' {
			return errors.New("expected string, got " + string(t.Kind()))
		}
		switch t.String() {
		default:
			d.SkipValue()
		}
	}
	_, _ = d.ReadToken()
	return nil
}
