// Code generated by go-gen-json. DO NOT EDIT.
package examples

import (
	"bytes"
	"encoding/json/jsontext"
	"errors"
)

func (p *NamedString) UnmarshalJSON(b []byte) error {
	d := jsontext.NewDecoder(bytes.NewReader(b))
	return p.UnmarshalJSONFrom(d)
}

func (p *NamedString) UnmarshalJSONFrom(d *jsontext.Decoder) error {
	var (
		t   jsontext.Token
		err error
	)
	t, err = d.ReadToken()
	if err != nil {
		return err
	} 
	if t.Kind() != '"' {
		return errors.New("expected string, got " + string(t.Kind()))
	}
	*p = NamedString(t.String())
	return nil
}
